Status(_api=<tweepy.api.API object at 0x05E4D390>,
_json={
'created_at': 'Mon Apr 16 03:45:19 +0000 2018',
 'id': 985725799893319680,
 'id_str': '985725799893319680',
 'text': 'I’m no cutie &gt;:c',
 'truncated': False,
 'entities': {
	'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': []
	},
 'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
 'in_reply_to_status_id': None,
 'in_reply_to_status_id_str': None,
 'in_reply_to_user_id': None,
 'in_reply_to_user_id_str': None,
 'in_reply_to_screen_name': None, 
 'user': {
	'id': 713251392568164352,
	'id_str': '713251392568164352',
	'name': 'Eclipse Wishes',
	'screen_name': 'Eclipse_782',
	'location': 'THE V-O-I-D',
	'description': "I exist. I'm an account no one cares about. Fan of many things. I forgot how to grammar. I’m not cool or cute.",
	'url': None,
	'entities': {'description': {'urls': []}},
	'protected': False,
	'followers_count': 1213,
	'friends_count': 499,
	'listed_count': 58,
	'created_at': 'Fri Mar 25 06:29:18 +0000 2016',
	'favourites_count': 281302,
	'utc_offset': -25200,
	'time_zone': 'Pacific Time (US & Canada)',
	'geo_enabled': False,
	'verified': False,
	'statuses_count': 205649,
	'lang': 'en',
	'contributors_enabled': False,
	'is_translator': False,
	'is_translation_enabled': False,
	'profile_background_color': 'F5F8FA',
	'profile_background_image_url': None,
	'profile_background_image_url_https': None,
	'profile_background_tile': False,
	'profile_image_url': 'http://pbs.twimg.com/profile_images/980623615828701184/wnwjiTf3_normal.jpg',
	'profile_image_url_https': 'https://pbs.twimg.com/profile_images/980623615828701184/wnwjiTf3_normal.jpg',
	'profile_banner_url': 'https://pbs.twimg.com/profile_banners/713251392568164352/1509764320', 
	'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED', 'profile_sidebar_fill_color': 'DDEEF6',
	'profile_text_color': '333333', 
	'profile_use_background_image': True, 
	'has_extended_profile': True,
	'default_profile': True, 
	'default_profile_image': False,
	'following': True,
	'follow_request_sent': False,
	'notifications': False, 
	'translator_type': 'regular'
	}, 
'geo': None,
'coordinates': None,
'place': None, 
'contributors': None,
'is_quote_status': False, 
'retweet_count': 0,
'favorite_count': 0,
'favorited': False, 
'retweeted': False, 
'lang': 'en'
}
)

 
